/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CollectorVM} from './CollectorVM.js';

/**
 * The AllOfSNMPCollectorCollectorVM model module.
 * @module model/AllOfSNMPCollectorCollectorVM
 * @version 1.1.0
 */
export class AllOfSNMPCollectorCollectorVM {
  /**
   * Constructs a new <code>AllOfSNMPCollectorCollectorVM</code>.
   * @alias module:model/AllOfSNMPCollectorCollectorVM
   * @class
   * @param province {} 
   */
  constructor(province) {
    this.province = province;
  }

  /**
   * Constructs a <code>AllOfSNMPCollectorCollectorVM</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfSNMPCollectorCollectorVM} obj Optional instance to populate.
   * @return {module:model/AllOfSNMPCollectorCollectorVM} The populated <code>AllOfSNMPCollectorCollectorVM</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfSNMPCollectorCollectorVM();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('ip'))
        obj.ip = ApiClient.convertToType(data['ip'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('province'))
        obj.province = ApiClient.convertToType(data['province'], Object);
    }
    return obj;
  }
}

/**
 * missing description
 * @member {Number} id
 */
AllOfSNMPCollectorCollectorVM.prototype.id = undefined;

/**
 * missing description
 * @member {String} ip
 */
AllOfSNMPCollectorCollectorVM.prototype.ip = undefined;

/**
 * missing description
 * @member {String} name
 */
AllOfSNMPCollectorCollectorVM.prototype.name = undefined;

/**
 * @member {Object} province
 */
AllOfSNMPCollectorCollectorVM.prototype.province = undefined;

