/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The CollectorVM model module.
 * @module model/CollectorVM
 * @version 1.1.0
 */
export class CollectorVM {
  /**
   * Constructs a new <code>CollectorVM</code>.
   * @alias module:model/CollectorVM
   * @class
   * @param province {Object} 
   */
  constructor(province) {
    this.province = province;
  }

  /**
   * Constructs a <code>CollectorVM</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectorVM} obj Optional instance to populate.
   * @return {module:model/CollectorVM} The populated <code>CollectorVM</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CollectorVM();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('ip'))
        obj.ip = ApiClient.convertToType(data['ip'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('province'))
        obj.province = ApiClient.convertToType(data['province'], Object);
    }
    return obj;
  }
}

/**
 * missing description
 * @member {Number} id
 */
CollectorVM.prototype.id = undefined;

/**
 * missing description
 * @member {String} ip
 */
CollectorVM.prototype.ip = undefined;

/**
 * missing description
 * @member {String} name
 */
CollectorVM.prototype.name = undefined;

/**
 * @member {Object} province
 */
CollectorVM.prototype.province = undefined;

