/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient.js";
import {CollectorVM} from '../model/CollectorVM.js';

/**
* CollectorVM service.
* @module api/CollectorVMApi
* @version 1.1.0
*/
export class CollectorVMApi {

    /**
    * Constructs a new CollectorVMApi. 
    * @alias module:api/CollectorVMApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addCollectorVM operation.
     * @callback moduleapi/CollectorVMApi~addCollectorVMCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds Collector VM
     * Adds Collector VM to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/CollectorVM} opts.body Inventory item to add
     * @param {module:api/CollectorVMApi~addCollectorVMCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addCollectorVM(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/collectorVM', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchCollectorVM operation.
     * @callback moduleapi/CollectorVMApi~searchCollectorVMCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CollectorVM>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches Collector VM
     * By passing in the appropriate options, you can search for available Collector VMs 
     * @param {module:api/CollectorVMApi~searchCollectorVMCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searchCollectorVM(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CollectorVM];

      return this.apiClient.callApi(
        '/collectorVM', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}