/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient.js";
import {CommunityStr} from '../model/CommunityStr.js';

/**
* CommunityStr service.
* @module api/CommunityStrApi
* @version 1.1.0
*/
export class CommunityStrApi {

    /**
    * Constructs a new CommunityStrApi. 
    * @alias module:api/CommunityStrApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addCommunityStr operation.
     * @callback moduleapi/CommunityStrApi~addCommunityStrCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds Monitored Objects
     * Adds Community Strings to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/CommunityStr} opts.body Inventory item to add
     * @param {module:api/CommunityStrApi~addCommunityStrCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addCommunityStr(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/CommunityStr', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searcCommunityStr operation.
     * @callback moduleapi/CommunityStrApi~searcCommunityStrCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CommunityStr>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches Community Strings
     * By passing in the appropriate options, you can search for available Community Strings 
     * @param {module:api/CommunityStrApi~searcCommunityStrCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searcCommunityStr(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CommunityStr];

      return this.apiClient.callApi(
        '/CommunityStr', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}