/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient.js";
import {KPIStats} from '../model/KPIStats.js';

/**
* KPIStats service.
* @module api/KPIStatsApi
* @version 1.1.0
*/
export class KPIStatsApi {

    /**
    * Constructs a new KPIStatsApi. 
    * @alias module:api/KPIStatsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addKPIstats operation.
     * @callback moduleapi/KPIStatsApi~addKPIstatsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds KPI Stats
     * Adds KPI stats to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/KPIStats} opts.body Inventory item to add
     * @param {module:api/KPIStatsApi~addKPIstatsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addKPIstats(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/KPIStats', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchKPIstats operation.
     * @callback moduleapi/KPIStatsApi~searchKPIstatsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/KPIStats>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches KPI Stats
     * By passing in the appropriate options, you can search for available KPIStats 
     * @param {module:api/KPIStatsApi~searchKPIstatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searchKPIstats(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [KPIStats];

      return this.apiClient.callApi(
        '/KPIStats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}