/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient.js";
import {Province} from '../model/Province.js';

/**
* Province service.
* @module api/ProvinceApi
* @version 1.1.0
*/
export class ProvinceApi {

    /**
    * Constructs a new ProvinceApi. 
    * @alias module:api/ProvinceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addProvince operation.
     * @callback moduleapi/ProvinceApi~addProvinceCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds Province
     * Adds Province to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/Province} opts.body Inventory item to add
     * @param {module:api/ProvinceApi~addProvinceCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addProvince(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/Province', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchProvince operation.
     * @callback moduleapi/ProvinceApi~searchProvinceCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Province>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches Province
     * By passing in the appropriate options, you can search for available Province 
     * @param {module:api/ProvinceApi~searchProvinceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searchProvince(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Province];

      return this.apiClient.callApi(
        '/Province', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}