/*
 * Meerkat Automation APIs
 * This API for quering and adding Meerkat SNMP Devices
 *
 * OpenAPI spec version: 1.1.0
 * Contact: emad.dawoud@telus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient.js";
import {SNMPCollector} from '../model/SNMPCollector.js';

/**
* SNMPCollector service.
* @module api/SNMPCollectorApi
* @version 1.1.0
*/
export class SNMPCollectorApi {

    /**
    * Constructs a new SNMPCollectorApi. 
    * @alias module:api/SNMPCollectorApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addSNMPCollector operation.
     * @callback moduleapi/SNMPCollectorApi~addSNMPCollectorCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds SNMP Collector
     * Adds SNMP Collector to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/SNMPCollector} opts.body Inventory item to add SNMPcCollector
     * @param {module:api/SNMPCollectorApi~addSNMPCollectorCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addSNMPCollector(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/SNMPCollector', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchSNMPCollector operation.
     * @callback moduleapi/SNMPCollectorApi~searchSNMPCollectorCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SNMPCollector>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches SNMP Collector
     * By passing in the appropriate options, you can search for available SNMP Collectors 
     * @param {module:api/SNMPCollectorApi~searchSNMPCollectorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searchSNMPCollector(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SNMPCollector];

      return this.apiClient.callApi(
        '/SNMPCollector', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}