name: integration

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  schedule:
    - cron: '33 20 * * *'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]


jobs:
  integration: 

    # You can just reference the main branch if you want but since we added release we will use that
   
#    uses: EmadDawoud/meerkat-auto-client-app/.github/workflows/integration.yml@master
 #   permissions:
  #    contents: read
   #   checks: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Trigger remote integration workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: EmadDawoud/meerkat-auto-client-app
          event-type: trigger-integration
          token: ${{ secrets.GITHUB_TOKEN }}

